### PR TITLE
The initializer `store` has been deprecated.

### PR DESCRIPTION
**Pull request by sebastianhelbig**
See https://www.emberjs.com/deprecations/ember-data/v2.x/#toc_id-ds-deprecated-initializers

### CODE REVIEW

**Comment by danwenzel** [comment]
Updates on this?  Looks like an easy 👍 

Ember 3.0 will break without this

**Comment by localpcguy** [comment]
@alexmngn this looks like a pretty minor update, any chance it can be merged as we are getting closer to v3?

**Comment by sebastianhelbig** [comment]
@alexmngn If you are not interested anymore in maintaining this, please let someone take over. It seems I am not the only one who still uses this addon :-)

**Comment by alexmngn** [comment]
@ktrhn I'm not maintaining this anymore, although I can merge this if you make Travis happy :)

**Comment by sebastianhelbig** [comment]
@alexmngn Done & Done :-) Addon is now up to date.

**Pull request merged**
